### ISSUE TITLE
Error: Valid email required

### ISSUE THREAD

**Issue by jodyheavener** [mozilla/fxa#10307]
Looks like this started happening recently, might be worth looking in to.

---

https://sentry.prod.mozaws.net/operations/fxa-content-server-prod/issues/12691324/?referrer=github_plugin

```
Error: Valid email required
  at toError (/bundle-fdac8446fb59e4d985ed1693009cebe0541f978d/app.bundle.fa.js:9:12467)
  at validate (/bundle-fdac8446fb59e4d985ed1693009cebe0541f978d/app.bundle.fa.js:9:233026)
  at o.a.fn.validate (/bundle-fdac8446fb59e4d985ed1693009cebe0541f978d/app.bundle.fa.js:9:293181)
  at showValidationErrors (/bundle-fdac8446fb59e4d985ed1693009cebe0541f978d/app.bundle.fa.js:1:23705)
  at _<.validateAndSubmit</< (/bundle-fdac8446fb59e4d985ed1693009cebe0541f978d/app.bundle.fa.js:1:22714)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-3931)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
