### ISSUE TITLE
`npm run test-remote` does not run locally for auth-server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#1064]
> ➜  fxa-auth-server git:(master) npm run test-remote                                                                 git:(master|)

> fxa-auth-server@1.136.3 test-remote /Users/shanetomlinson/development/fxa/packages/fxa-auth-server
> MAILER_HOST=restmail.net MAILER_PORT=80 CORS_ORIGIN=http://baz mocha --timeout=300000 test/remote

> internal/modules/cjs/loader.js:583
    throw err;
    ^

> Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/fxa-auth-db-mysql/db-server/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/fxa-auth-db-mysql/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/test/test_server.js:11:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/test/remote/account_create_tests.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/shanetomlinson/development/fxa/packages/fxa-auth-server/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/shanetomlinson/development/fxa/packages/fxa-auth-server/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa-auth-server@1.136.3 test-remote: `MAILER_HOST=restmail.net MAILER_PORT=80 CORS_ORIGIN=http://baz mocha --timeout=300000 test/remote`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fxa-auth-server@1.136.3 test-remote script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shanetomlinson/.fxacache/_logs/2019-05-10T09_31_18_484Z-debug.log
➜  fxa-auth-server git:(master)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-83)
┆Issue Number: FXA-83

**Comment by shane-tomlinson** [comment]
@philbooth, @dannycoates - Any ideas why is there an fxa-auth-db-mysql within the fxa-auth-server directory when it could just use the one from packages?

> /Users/shanetomlinson/development/fxa/packages/fxa-auth-server/fxa-auth-db-mysql/index.js:6:16

**Comment by shane-tomlinson** [comment]
> Any ideas why is there an fxa-auth-db-mysql within the fxa-auth-server directory when it could just use the one from packages?

https://github.com/mozilla/fxa/blob/f6d86ea735a928dd14337323d75b768a60c7bca0/packages/fxa-auth-server/scripts/test-local.sh#L17

**Comment by shane-tomlinson** [comment]
So, if the auth-db has already been cloned, no attempt to re-clone it is done, nor is any attempt to update the package done, which could lead to this problem.

**Comment by philbooth** [comment]
> @philbooth, @dannycoates - Any ideas why is there an fxa-auth-db-mysql within the fxa-auth-server directory...

#796. Also see discussion in #941.

> ...when it could just use the one from packages?

It can't just use the one from `/packages` because that doesn't exist inside the Docker container, so won't work in CI. Cloning the auth db was an urgent hack I put in place so that tests would run against the correct db code instead of the old, stale fxa-auth-db-mysql repo. I fully support any efforts to move away from it.
