### ISSUE TITLE
Intermittent content-server build error

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa#1188]
I have since this failure about at least 3 times in the past couple days.

```
Waiting for parallel builds to finish...
.............................................................................................................................................................
Parallel build failed
```

It occurs when building the content-server.

**Comment by philbooth** [comment]
> ```
> Parallel build failed
> ```

That's not the error btw, you need to open the other tabs to see the actual failure. Fwiw, I noticed this one just now:

```
× firefox on linux 4.15.0-1035-aws - cached signin - sign in once, use a different account (3.875s)
    UnknownError: [GET http://localhost:4444/wd/hub/session/b3df1ca8-2f57-44d5-b204-b32a08680077/screenshot] Failed to decode response from marionette
    Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
    System info: host: 'eb3d9425be2a', ip: '192.168.16.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '1.8.0_212'
    Driver info: driver.version: unknown
      at Command.<anonymous>  <tests/functional/lib/helpers.js:91:24>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:72:34>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:68:10>
      at Test.sign in once, use a different account [as test]  <tests/functional/sign_in_cached.js:136:10>
      at <src/lib/Test.ts:263:51>

Suite firefox on linux 4.15.0-1035-aws - cached signin FAILED
SessionNotCreatedException: [GET http://localhost:4444/wd/hub/session/b3df1ca8-2f57-44d5-b204-b32a08680077/screenshot] Tried to run command without establishing a connection
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'eb3d9425be2a', ip: '192.168.16.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '1.8.0_212'
Driver info: driver.version: unknown
  at Command.<anonymous>  <tests/functional/lib/helpers.js:91:24>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:72:34>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:68:10>
  at Suite.beforeEach  <tests/functional/sign_in_cached.js:53:8>
  at <src/lib/Suite.ts:383:26>
  at runLifecycleMethod  <src/lib/Suite.ts:351:13>
  at next  <src/lib/Suite.ts:522:32>
(ノಠ益ಠ)ノ彡┻━┻
SessionNotCreatedException: [DELETE http://localhost:4444/wd/hub/session/b3df1ca8-2f57-44d5-b204-b32a08680077] Tried to run command without establishing a connection
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'eb3d9425be2a', ip: '192.168.16.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '1.8.0_212'
Driver info: driver.version: unknown
  at <src/lib/ProxiedSession.ts:79:31>
  at Suite.after  <src/lib/executors/Node.ts:524:28>
  at <src/lib/Suite.ts:384:26>
  at runLifecycleMethod  <src/lib/Suite.ts:351:13>
  at after  <src/lib/Suite.ts:453:13>
  at <src/lib/Suite.ts:670:47>
```

**Comment by vbudhram** [comment]
> (ノಠ益ಠ)ノ彡┻━┻

Got it again in https://circleci.com/gh/mozilla/fxa/21497#tests/containers/3

**Comment by clouserw** [comment]
I think this has been addressed.  Please reopen if not.
