### ISSUE TITLE
[payments] Filter out errors from extensions, third party scripts, etc.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13533]
The error below is an example error we should ignore; in general, there are a lot of errors from other scripts than ours that create a lot of noise in Sentry. We can safely ignore most of these.

Examples: from web extensions, third party scripts and local file paths.

Error: The string did not match the expected pattern.
Sentry Issue: [FXA-PAYMENTS-AK](https://sentry.io/organizations/mozilla/issues/3402629929/?referrer=jira_integration)

```java
Error: The string did not match the expected pattern.
  at None (safari-extension://68ADDB30-5B2F-4CDA-B14C-4FABC80BFBDF/pageContext/commons.js:1:4258775)
  at tryCatcher (safari-extension://68ADDB30-5B2F-4CDA-B14C-4FABC80BFBDF/pageContext/commons.js:1:4351526)
  at None (safari-extension://68ADDB30-5B2F-4CDA-B14C-4FABC80BFBDF/pageContext/commons.js:1:4297930)
  at None (safari-extension://68ADDB30-5B2F-4CDA-B14C-4FABC80BFBDF/pageContext/commons.js:1:4258567)
  at handleMessage (safari-extension://68ADDB30-5B2F-4CDA-B14C-4FABC80BFBDF/pageContext/commons.js:1:4258895)
...
(2 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5473)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
