### ISSUE TITLE
[subplat] Error: Should not already be working.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#13879]
Sentry Issue: [FXA-PAYMENTS-CM](https://sentry.io/organizations/mozilla/issues/3477237842/?referrer=jira_integration)

```
Error: Should not already be working.
  at b (../../../node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
  at If (../../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at cg (../../../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at fg (../../../node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at X (../../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js:17:184)
...
(1 additional frame(s) were not displayed)
```

Additional Notes

* Found a thread discussing this issue. Upgrading to React 18 seems to resolve the problem. https://github.com/facebook/react/issues/17355

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-5677)

**Comment by cknowles-admin** [comment]
FxA is no longer synchronizing all issues between Jira and Github.  We are closing open issues and will selectively synchronize in the future.
