### ISSUE TITLE
Chaining operator breaking l10n-extract (Fatal error: Unexpected token (647:35))

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fxa#14057]
npx grunt l10n-extract is currently broken, so there's no way to extract strings for localization.
This is a repeat of a previous issue (#13893). 

The chaining operator syntax is not supported by [jsxextract ](https://github.com/mozilla/fxa/issues/13893#issuecomment-1209975035)which is used in the l10n-extract script.

[This commit](https://github.com/mozilla/fxa/commit/2d81c82c1c610129eae24cb96d8f03170c8173ad) is causing the l10n-extract to break.

```
Running "jsxextract" task
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
CRITICAL fxa-content-server.uncaughtException: SyntaxError: Unexpected token (647:35)
    at Parser.pp$4.raise (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseExprAtom (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2196:10)
    at Parser.parseExprAtom (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/inject.js:399:24)
    at Parser.pp$3.parseExprSubscripts (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseMaybeConditional (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1954:28)
    at Parser.pp$3.parseMaybeAssign (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parsePropertyValue (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2443:87)
    at Parser.pp$3.parseProperty (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2434:8)
    at Parser.pp$3.parseObj (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2380:23)
    at Parser.pp$3.parseExprAtom (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/node_modules/acorn/dist/acorn.js:2179:17)
    at Parser.parseExprAtom (/home/runner/work/fxa-content-server-l10n/fxa-content-server-l10n/fxa-code/node_modules/acorn-jsx/inject.js:399:24)
Fatal error: Unexpected token (647:35)
```
This issue will more than likely crop up again (at least until gettext gets converted to Fluent). I would like to request the following fixes:

1. The chaining operators added in [this commit](https://github.com/mozilla/fxa/commit/2d81c82c1c610129eae24cb96d8f03170c8173ad) need to be removed in order to extract l10n strings.
2. ~~Add a build step with the l10n-extract process to catch this unsupported syntax early, rather than l10n discovering the issue when its time to import strings for localization.~~

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-5865)

**Comment by flodolo** [comment]
For 2, I'd suggest to use and adapt [this workflow](https://github.com/mozilla/fxa-content-server-l10n/blob/main/.github/workflows/l10n_extract.yaml) (very minor changes):
- Make it run on pull requests, no need for push
- Need to swap the two repos
- Don't need the part about committing and creating the PR

**Comment by bcolsson** [comment]
I'm currently working to see if I can adapt our workflow as a fix for 2. However, 1 still needs to be fixed in order for us to extract strings for localization.

1. The chaining operators added in [this commit](https://github.com/mozilla/fxa/commit/2d81c82c1c610129eae24cb96d8f03170c8173ad) need to be removed in order to extract l10n strings.

**Comment by clouserw** [comment]
The jira issue was resolved but this wasn't.  The sync is fixed now, so marking this fixed.
