### ISSUE TITLE
Content server fails to start with JSON Syntax error in popular-email-domains.json

### ISSUE THREAD

**Issue by boerngen-schmidt** [mozilla/fxa#1645]
Hello,

I installed fxa using the instructions from the read me in my local WSL Ubuntu 18.04 and the content server fails to start due to the following error message:

```
3|content- | raven@2.6.1 alert: no DSN provided, error reporting disabled
3|content- | SyntaxError: /mnt/c/Development/git/fxa/packages/fxa-content-server/app/scripts/lib/popular-email-domains.json: Unexpected token . in JSON at position 0
3|content- |     at JSON.parse (<anonymous>)
3|content- |     at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|content- |     at require (internal/modules/cjs/helpers.js:25:18)
3|content- |     at Object.<anonymous> (/mnt/c/Development/git/fxa/packages/fxa-content-server/app/scripts/lib/constants.js:5:29)
3|content- |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|content- |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|content- |     at require (internal/modules/cjs/helpers.js:25:18)
3|content- |     at Object.<anonymous> (/mnt/c/Development/git/fxa/packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/token-code.js:8:19)
3|content- |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|content- |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|content- |     at require (internal/modules/cjs/helpers.js:25:18)
3|content- |     at Object.<anonymous> (/mnt/c/Development/git/fxa/packages/fxa-content-server/app/scripts/lib/experiments/grouping-rules/index.js:19:3)
3|content- |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|content- |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|content- |     at require (internal/modules/cjs/helpers.js:25:18)
3|content- |     at Object.<anonymous> (/mnt/c/Development/git/fxa/packages/fxa-content-server/server/lib/validation.js:12:5)
3|content- |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|content- |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|content- |     at require (internal/modules/cjs/helpers.js:25:18)
3|content- |     at Object.<anonymous> (/mnt/c/Development/git/fxa/packages/fxa-content-server/server/lib/routes/get-update-firefox.js:12:20)
3|content- |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|content- |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Module.require (internal/modules/cjs/loader.js:690:17)
3|content- |     at require (internal/modules/cjs/helpers.js:25:18)
3|content- |     at module.exports (/mnt/c/Development/git/fxa/packages/fxa-content-server/server/lib/routes.js:44:5)
3|content- |     at Object.<anonymous> (/mnt/c/Development/git/fxa/packages/fxa-content-server/server/bin/fxa-content-server.js:52:40)
3|content- |     at Module._compile (internal/modules/cjs/loader.js:776:30)
3|content- |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
3|content- |     at Module.load (internal/modules/cjs/loader.js:653:32)
3|content- |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
3|content- |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
3|content- |     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
3|content- |     at startup (internal/bootstrap/node.js:283:19)
3|content- |     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by boerngen-schmidt** [comment]
I figured out the problem.

When cloning the repo under windows, what I initially did, the symlink does not get created, but a file with the content
```../../../node_modules/fxa-shared/email/popularDomains.json```
which then causes the error above.

Checking out the repo under WSL (Ubuntu 18.04) itself does create the symlink correctly thus the build works as expected.

I think there are two possible solutions:
1. Close the ticket and add that Windows does have some troubles with the repo, especially with symlinks
2. Create a fxa-base image, that the services will use to when getting build, which provides fxa-share, fxa-i18n etc. This ensures that all shared files are present during build time in the docker image and symlinking is not needed since the resource will be present.

**Comment by clouserw** [comment]
Thanks for filing this and your proposed solutions.  We have a couple people that have this set up on Windows and are using WSL successfully, as you mention.  Let's add using WSL as a requirement to the documentation.
