### ISSUE TITLE
Sorry for bothering but need help

### ISSUE THREAD

**Issue by DevDorrejo** [mozilla/fxa#1683]
Hello and sorry.

i am using openSUSe Leap 15.1 to setup the service, i install all dependency, the npm install --verbose go smooth, now when i make ./pm2 start server.json all service go online, when did a status got some process errored see issue #1599.

- Ignoring that i did npm start, everything is configured like the README.md, start a new firefox instances, now when try sign up, fill all with a existing email, press create user and red banner appear saying unavailable system, go to ./pm2 logs and this appear

> 1|auth-server db memory PORT 8000  | {"Timestamp":1562450494959000000,"Logger":"fxa-auth-db-server","Type":"bin.server.mem","Severity":6,"Pid":19358,"EnvVersion":"2.0","Fields":{"rss":71032832,"heapTotal":22843392,"heapUsed":17717872,"external":50991}}
> 
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: stat {"stat":"mem","rss":210997248,"heapUsed":69191288}
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: stat {"stat":"scrypt","maxPending":0,"numPending":0,"numPendingHWM":0}
> 3|content-server PORT 3030         | fxa-content-server.server.requests.INFO: route GET /images/icon-show-password.svg 11.101 200
> 3|content-server PORT 3030         | fxa-content-server.server.requests.INFO: route GET /images/spinnerwhite.svg 0.692 304
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: metrics.context.validate {"valid":true}
> 2|auth-server key server PORT 9000 | fxa-auth-server.ERROR: server.EndpointError {"message":"127.0.0.1:8000 error: connect ECONNREFUSED 127.0.0.1:8000","reason":"connect ECONNREFUSED 127.0.0.1:8000","method":"GET"}
> 
> 2|auth-server key server PORT 9000 | fxa-auth-server.ERROR: geodb.1 {"err":"Unable to fetch data"}
> 2|auth-server key server PORT 9000 | fxa-auth-server.ERROR: request.summary {"status":500,"errno":203,"path":"/v1/account/create","lang":"es-DO,en-US;q=0.7,en;q=0.3","agent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0)Gecko/20100101 Firefox/60.0","remoteAddressChain":["127.0.0.1"],"t":46,"uid":"00","keys":false,"method":"post","email":"wedcjuegos@gmail.com","stack":"Error: A backend service request failed.\n    at Function.AppError.backendServiceFailure (/home/wedc/fxa/packages/fxa-auth-server/lib/error.js:1193:10)\n    at Function.AppError.translate (/home/wedc/fxa/packages/fxa-auth-server/lib/error.js:210:22)\n    at server.ext.request (/home/wedc/fxa/packages/fxa-auth-server/lib/server.js:284:24)\n    at module.exports.internals.Manager.execute (/home/wedc/fxa/packages/fxa-auth-server/node_modules/hapi/lib/toolkit.js:35:106)\n    at Request._invoke (/home/wedc/fxa/packages/fxa-auth-server/node_modules/hapi/lib/request.js:293:55)\n    at Request._postCycle (/home/wedc/fxa/packages/fxa-auth-server/node_modules/hapi/lib/request.js:356:86)"}
> 
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: flowEvent {"event":"route./account/create.500.203","locale":"es","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","time":1562450509609,"device_id":"4eaae2b5ad7040a0bd722eb44943b234","flow_id":"f9b8f16a443086303425a23d300846abc53145a4fe2f88c23001e2d7aef4e81f","flow_time":80757,"flowBeginTime":1562450428852}
> 3|content-server PORT 3030         | fxa-content-server.server.requests.INFO: route POST /metrics-errors?sentry_version=7&sentry_client=raven-js%2F3.13.0&sentry_key=__API_KEY__ 3.705 200
> 1|auth-server db memory PORT 8000  | {"Timestamp":1562450509959000000,"Logger":"fxa-auth-db-server","Type":"bin.server.mem","Severity":6,"Pid":19358,"EnvVersion":"2.0","Fields":{"rss":71036928,"heapTotal":22843392,"heapUsed":17873872,"external":50991}}
> 3|content-server PORT 3030         | fxa-content-server.server.requests.INFO: route POST /metrics 2.323 200
> 3|content-server PORT 3030         | {"time":"2019-07-06T22:00:00.000Z","op":"client.metrics","hostname":"DevWEDC","pid":19837,"v":1,"lang":"es","agent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","duration":84193,"context":"web","broker":"web","entrypoint":"none","service":"none","migration":"none","events":["mailcheck.triggered","signup.submit","error.signup.auth.203"],"event_durations":[75298,80428,80976],"screen.width":1920,"screen.height":1080}
> 3|content-server PORT 3030         | fxa-content-server.server.geo.ERROR: geodb.error Error: Unable to fetch data
> 3|content-server PORT 3030         |     at /home/wedc/fxa/packages/fxa-content-server/node_modules/fxa-geodb/lib/fxa-geodb.js:28:13
> 3|content-server PORT 3030         |     at module.exports.request (/home/wedc/fxa/packages/fxa-content-server/server/lib/geo-locate.js:20:12)
> 3|content-server PORT 3030         |     at metricsRequest (/home/wedc/fxa/packages/fxa-content-server/server/lib/flow-event.js:81:22)
> 3|content-server PORT 3030         |     at process.nextTick (/home/wedc/fxa/packages/fxa-content-server/server/lib/routes/post-metrics.js:202:9)
> 3|content-server PORT 3030         |     at process._tickCallback (internal/process/next_tick.js:61:11)
> 3|content-server PORT 3030         | fxa-content-server.INFO: amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_reg - submit","time":1562450509393,"device_id":"4eaae2b5ad7040a0bd722eb44943b234","session_id":1562450428852,"app_version":"140","language":"es","os_name":"Linux","event_properties":{},"user_properties":{"flow_id":"f9b8f16a443086303425a23d300846abc53145a4fe2f88c23001e2d7aef4e81f","ua_browser":"Firefox","ua_version":"60.0"}}
> 
> 3|content-server PORT 3030         | {"event":"flow.signup.submit","flow_id":"f9b8f16a443086303425a23d300846abc53145a4fe2f88c23001e2d7aef4e81f","flow_time":80541,"hostname":"DevWEDC","locale":"es","op":"flowEvent","pid":19837,"time":"2019-07-06T22:01:49.393Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","v":1,"context":"web"}
> 
> 3|content-server PORT 3030         | {"event":"flow.signup.attempt","flow_id":"f9b8f16a443086303425a23d300846abc53145a4fe2f88c23001e2d7aef4e81f","flow_time":80563,"hostname":"DevWEDC","locale":"es","op":"flowEvent","pid":19837,"time":"2019-07-06T22:01:49.415Z","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","v":1,"context":"web"}
> 
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: stat {"stat":"mem","rss":212385792,"heapUsed":69984368}  
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: stat {"stat":"scrypt","maxPending":0,"numPending":0,"numPendingHWM":0}
> 1|auth-server db memory PORT 8000  | {"Timestamp":1562450524959000000,"Logger":"fxa-auth-db-server","Type":"bin.server.mem","Severity":6,"Pid":19358,"EnvVersion":"2.0","Fields":{"rss":71041024,"heapTotal":22843392,"heapUsed":18027096,"external":50991}}
> 
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: stat {"stat":"mem","rss":212389888,"heapUsed":70170656}
> 2|auth-server key server PORT 9000 | fxa-auth-server.INFO: stat {"stat":"scrypt","maxPending":0,"numPending":0,"numPendingHWM":0}
> 1|auth-server db memory PORT 8000  | {"Timestamp":1562450539960000000,"Logger":"fxa-auth-db-server","Type":"bin.server.mem","Severity":6,"Pid":19358,"EnvVersion":"2.0","Fields":{"rss":71041024,"heapTotal":22843392,"heapUsed":17224560,"external":50991}}

- now i decide run npm test, and it's fail too:

> fxa@2.0.0 test /home/wedc/fxa
> lerna run test
lerna notice cli v3.15.0
lerna info versioning independent
lerna info Executing command in 15 packages: "npm run test"
lerna ERR! npm run test exited 1 in 'browserid-verifier'
lerna ERR! npm run test stdout:
> browserid-verifier@0.10.1 test /home/wedc/fxa/packages/browserid-verifier
> mocha --exit -t 5000 -R spec tests/*.js
lerna ERR! npm run test stderr:
internal/modules/cjs/loader.js:583
throw err;
^
Error: Cannot find module 'jshint'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/home/wedc/fxa/packages/browserid-verifier/tests/jshint.js:12:12)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at /home/wedc/fxa/packages/browserid-verifier/node_modules/mocha/lib/mocha.js:250:27
at Array.forEach (<anonymous>)
at Mocha.loadFiles (/home/wedc/fxa/packages/browserid-verifier/node_modules/mocha/lib/mocha.js:247:14)
at Mocha.run (/home/wedc/fxa/packages/browserid-verifier/node_modules/mocha/lib/mocha.js:576:10)
at Object.<anonymous> (/home/wedc/fxa/packages/browserid-verifier/node_modules/mocha/bin/_mocha:637:18)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browserid-verifier@0.10.1 test: `mocha --exit -t 5000 -R spec tests/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browserid-verifier@0.10.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wedc/.npm/_logs/2019-07-06T22_10_48_998Z-debug.log
lerna ERR! npm run test exited 1 in 'browserid-verifier'
lerna WARN complete Waiting for 8 child processes to exit. CTRL-C to exit immediately.
npm ERR! Test failed.  See above for more details.

[2019-07-06T22_10_48_998Z-debug.log](https://github.com/mozilla/fxa/files/3365082/2019-07-06T22_10_48_998Z-debug.log)

[2019-07-06T22_10_49_411Z-debug.log](https://github.com/mozilla/fxa/files/3365080/2019-07-06T22_10_49_411Z-debug.log)

**Comment by DevDorrejo** [comment]
the solution:  #1599
