### ISSUE TITLE
[train-140] exceptions thrown with production clients

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1697]
Canary auth server had errors and has been pulled out.

Error on route `/v1/account/devices` is:

```
ValidationError: \"value\" at position 0 fails because [child \"location\" fails 
   because [\"countryCode\" is not allowed]]
    at Object.exports.process (/app/node_modules/joi/lib/errors.js:201:19)
    at internals.Array._validateWithOptions (/app/node_modules/joi/lib/types/any/index.js:722:31)
    at module.exports.internals.Any.root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:146:23)
    at exports.response (/app/node_modules/hapi/lib/validation.js:173:31)
    at Request._postCycle (/app/node_modules/hapi/lib/request.js:356:68)
    at Request._reply (/app/node_modules/hapi/lib/request.js:335:20)
    at Request._execute (/app/node_modules/hapi/lib/request.js:171:14)
```

**Comment by philbooth** [comment]
Whoops, I duped this in #1698. But since that one has a PR open against it already, I'm closing this instead.
