### ISSUE TITLE
TypeError: crypto.generateKeyPairSync is not a function

### ISSUE THREAD

**Issue by DocMAX** [mozilla/fxa#1902]
Linux server 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux

```
/home/fxcloud/fxa/packages/fxa-auth-server/fxa-oauth-server/lib/keys.js:163
  const kp = crypto.generateKeyPairSync('rsa', {
                    ^

TypeError: crypto.generateKeyPairSync is not a function
    at Object.generatePrivateKey (/home/fxcloud/fxa/packages/fxa-auth-server/fxa-oauth-server/lib/keys.js:163:21)
    at main (/home/fxcloud/fxa/packages/fxa-auth-server/fxa-oauth-server/scripts/gen_keys.js:67:24)
    at Object.<anonymous> (/home/fxcloud/fxa/packages/fxa-auth-server/fxa-oauth-server/scripts/gen_keys.js:88:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa@2.0.0 postinstall: `_scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fxa@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fxcloud/.npm/_logs/2019-07-23T08_48_48_167Z-debug.log
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-230)
┆Issue Number: FXA-230

**Comment by shane-tomlinson** [comment]
@DocMAX - are you using Node 10? That's the only version of node we support at the moment.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

->expired
