### ISSUE TITLE
[latest.dev] 500 error on GET /v1/accounts

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#1954]
Have an new account, and load settings panel:

An xhr calls GET on https://latest.dev.lcip.org/auth/v1/account and gets back a 500 with errno 999 and Interrnal Server Error. In the auth server logs, I have:
```
"stack":"ValidationError: child \"subscriptions\" fails because [\"subscriptions\" must be an array]
    at Object.exports.process (/app/node_modules/hapi/node_modules/joi/lib/errors.js:201:19)
    at internals.Object._validateWithOptions (/app/node_modules/hapi/node_modules/joi/lib/types/any/index.js:751:31)
    at module.exports.internals.Any.root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:146:23)
    at exports.response (/app/node_modules/hapi/lib/validation.js:173:31)
    at Request._postCycle (/app/node_modules/hapi/lib/request.js:356:68)
    at Request._reply (/app/node_modules/hapi/lib/request.js:335:20)
    at Request._execute (/app/node_modules/hapi/lib/request.js:171:14)"}}
```

**Comment by jrgm** [comment]
The settings panel is unusable after that erro.

**Comment by lmorchard** [comment]
Looks like we're expecting the wrong error message text in the auth-server subhub client, which is likely since there's a `// TODO` comment around there. And it looks like the new `/v1/accounts` route is the first actual user of the bit where this happens. 😓  Working on a fix right now.
