### ISSUE TITLE
Failing functional test:  signin - signin with a second sign-up tab open

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2001]
> firefox on mac 18.7.0 - signin - signin with a second sign-up tab open (24.236s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/1846c87d-2510-2a4a-b6e5-bfd88bbf8e23/element / {"using":"css selector","value":"#fxa-settings-header"}] Unable to locate element: #fxa-settings-header
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '192.168.1.229', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:191:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.signin with a second sign-up tab open [as test] @ tests/functional/sign_in.js:187:10
      @ src/lib/Test.ts:263:51

This started (or was uncovered by) either yesterday or this morning. I suspect the test has always been incorrect, we've just never noticed it.

**Comment by shane-tomlinson** [comment]
I've been doing a bisect and the failure starts with 2943349f27cb3299c4bf39ab2eb769fa8873fdd8, for some reason clearing the memory is interfering with the test.

**Comment by shane-tomlinson** [comment]
!@$!@%!@ - This happens because localStorage between the two tabs has been isolated because `window(1)` is opened from `about:memory`.

`window(1)` is opened using [openSignUpInNewTab](https://github.com/mozilla/fxa/blob/8ca0616827b3ae25e53594b9d9d0cb49e37647fb/packages/fxa-content-server/tests/functional/lib/helpers.js#L1293) which uses `window.open`. `window.open` is run within the `about:memory` process. Since `about:memory` is special browser content, it is likely content isolated from a normal tab, and any tabs it opens are also content isolated. This means any tabs opened from `about:memory` have totally separate localStorage stores to a tab opened by the user. 

Because of the isolated localStorage stores, none of the session info needed by `window(1)` is stored in localStorage.
