### ISSUE TITLE
auth-server: /v1/account failing because subscriptions is not an array

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2006]
Saw this on latest while trying to help @LZoog debug some errors:

> {"Timestamp":1564505500740000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":7,"EnvVersion":"2.0","Fields":{"status":500,"errno":999,"path":"/auth/v1/account","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0","remoteAddressChain":"[\"80.47.44.108\",\"172.31.27.168\",\"127.0.0.1\"]","t":13,"uid":"814a568ffb9343dab8bd780ee151c429","keys":false,"method":"get","email":"stomlinson@mozilla.com","stack":"ValidationError: child \"subscriptions\" fails because [\"subscriptions\" must be an array]\n    at Object.exports.process (/app/node_modules/hapi/node_modules/joi/lib/errors.js:201:19)\n    at internals.Object._validateWithOptions (/app/node_modules/hapi/node_modules/joi/lib/types/any/index.js:751:31)\n    at module.exports.internals.Any.root.validate (/app/node_modules/hapi/node_modules/joi/lib/index.js:146:23)\n    at exports.response (/app/node_modules/hapi/lib/validation.js:173:31)\n    at Request._postCycle (/app/node_modules/hapi/lib/request.js:356:68)\n    at Request._reply (/app/node_modules/hapi/lib/request.js:335:20)\n    at Request._execute (/app/node_modules/hapi/lib/request.js:171:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}}

cc @philbooth and @lmorchard

**Comment by shane-tomlinson** [comment]
ref #1987

**Comment by shane-tomlinson** [comment]
on latest, both `SUBSCRIPTIONS_ENABLED=true` and `SUBHUB_ENABLED=true`, so it looks like somehow subhub might be returning `undefined`?
