### ISSUE TITLE
auth-server: /v1/oauth/token failing on latest

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2007]
> {"Timestamp":1564507421466000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":7,"EnvVersion":"2.0","Fields":{"status":500,"errno":203,"path":"/auth/v1/oauth/token","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0","remoteAddressChain":"[\"80.47.44.108\",\"172.31.27.168\",\"127.0.0.1\"]","t":156,"uid":"814a568ffb9343dab8bd780ee151c429","keys":false,"method":"post","email":"stomlinson@mozilla.com","stack":"Error: A backend service request failed.\n    at Function.AppError.backendServiceFailure (/app/lib/error.js:1203:10)\n    at sendRequest (/app/lib/backendService.js:177:2

ref #2006

It looks like the oauth server isn't running on latest?

**Comment by vladikoff** [comment]
@shane-tomlinson 

> fxa-oauth-server.CRITICAL: uncaughtException AssertionError [ERR_ASSERTION]: openid.key is missing; bailing out in a cowardly fashion...
    at Object.<anonymous> (/app/fxa-oauth-server/lib/keys.js:92:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/fxa-oauth-server/lib/jwt.js:7:62)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/fxa-oauth-server/lib/jwt_access_token.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by vladikoff** [comment]
Probably need to tweak for https://github.com/mozilla/fxa/pull/1997
