### ISSUE TITLE
Failing functional test: `send_sms - learn more`

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2044]
CircleCI:

```
Screenshot saved at: https://screencap.co.uk/images/f2633bac6176ab9eb9c41e30f0c74404df867a65.png
× firefox on linux 4.15.0-1035-aws - send_sms - learn more (21.47s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/a7ab055d-0e66-4b5d-bf5c-88c0e60d135b/element / {"using":"css selector","value":"#websites-notice"}] Unable to locate element: #websites-notice
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: '613452ade481', ip: '192.168.224.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '11.0.4'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:191:22
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.learn more [as test] @ tests/functional/send_sms.js:178:10
      @ src/lib/Test.ts:263:51
```

**Comment by vladikoff** [comment]
the selector is still on https://www.mozilla.org/en-US/privacy/websites/#campaigns 

maybe the page failed to load?

**Comment by chenba** [comment]
I see the new selector `#firefox-notice`.  I'll update the test.
