### ISSUE TITLE
`grunt l10n-extract` failing in the content server

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2067]
```bash
➜  fxa-content-server git:(master) grunt l10n-extract                                                                                                                                   git:(master|)
Running "clean:app" (clean) task
>> 0 paths cleaned.

Running "clean:dist" (clean) task
>> 6 paths cleaned.

Running "clean:tos_pp" (clean) task
>> 0 paths cleaned.

Running "jsxextract" task
fxa-content-server.CRITICAL: uncaughtException SyntaxError: Unexpected token (107:12)
  at Parser.pp$4.raise (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2757:13)
  at Parser.pp.unexpected (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:647:8)
  at Parser.pp$3.parseIdent (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2712:10)
  at Parser.pp$3.parsePropertyName (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2496:105)
  at Parser.pp$3.parseProperty (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2426:8)
  at Parser.pp$3.parseObj (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2380:23)
  at Parser.pp$3.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2179:17)
  at Parser.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn-jsx/inject.js:399:24)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2047:19)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parseExprList (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2663:20)
  at Parser.pp$3.parseSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2075:29)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2050:21)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parseExprList (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2663:20)
  at Parser.pp$3.parseSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2075:29)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2050:21)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parsePropertyValue (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2443:87)
  at Parser.pp$3.parseProperty (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2434:8)
  at Parser.pp$3.parseObj (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2380:23)
  at Parser.pp$3.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2179:17)
  at Parser.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn-jsx/inject.js:399:24)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2047:19)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parseExprList (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2663:20)
  at Parser.pp$3.parseSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2075:29)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2050:21)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parseExpression (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1896:19)
  at Parser.pp$1.parseStatement (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:815:45)
  at Parser.pp$1.parseBlock (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1112:23)
  at Parser.pp$3.parseFunctionBody (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2600:22)
  at Parser.pp$1.parseFunction (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1219:8)
  at Parser.pp$3.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2133:21)
  at Parser.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn-jsx/inject.js:399:24)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2047:19)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parsePropertyValue (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2443:87)
  at Parser.pp$3.parseProperty (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2434:8)
  at Parser.pp$3.parseObj (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2380:23)
  at Parser.pp$3.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2179:17)
  at Parser.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn-jsx/inject.js:399:24)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2047:19)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parseExpression (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1896:19)
  at Parser.pp$1.parseReturnStatement (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:946:31)
  at Parser.pp$1.parseStatement (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:781:35)
  at Parser.pp$1.parseBlock (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1112:23)
  at Parser.pp$3.parseFunctionBody (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2600:22)
  at Parser.pp$1.parseFunction (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1219:8)
  at Parser.pp$3.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2184:17)
  at Parser.parseExprAtom (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn-jsx/inject.js:399:24)
  at Parser.pp$3.parseExprSubscripts (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2047:19)
  at Parser.pp$3.parseMaybeUnary (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:2024:17)
  at Parser.pp$3.parseExprOps (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1966:19)
  at Parser.pp$3.parseMaybeConditional (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1949:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1925:19)
  at Parser.pp$3.parseMaybeAssign (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1935:23)
  at Parser.pp$3.parseExpression (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:1896:19)
  at Parser.pp$1.parseStatement (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:815:45)
  at Parser.pp$1.parseTopLevel (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:706:23)
  at Parser.parse (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:551:15)
  at Object.parse (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/acorn/dist/acorn.js:5288:37)
  at /Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/jsxgettext/lib/jsxgettext.js:189:27
  at Array.forEach (<anonymous>:null:null)
  at parse (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/jsxgettext/lib/jsxgettext.js:169:24)
  at Object.gen [as generate] (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/jsxgettext/lib/jsxgettext.js:261:35)
  at /Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/jsxgettext-recursive-next/index.js:61:30
  at Array.forEach (<anonymous>:null:null)
  at Walker.<anonymous> (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/jsxgettext-recursive-next/index.js:41:26)
  at Walker.emit (events.js:203:15)
  at Walker._wNext (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:278:10)
  at Walker._wNext (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:273:17)
  at Walker._wNext (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:273:17)
  at Walker._wOnEmitDone (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:125:8)
  at nextWhenReady (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/node-type-emitter.js:72:29)
  at Object.emitPluralEvents [as emitNodeTypeGroups] (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/node-type-emitter.js:80:5)
  at Walker._wPostFilesHandler (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:137:17)
  at /Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/foreachasync/forEachAsync.js:15:16
  at Array.forEach (<anonymous>:null:null)
  at Walker.next [as _wCurFileCallback] (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/foreachasync/forEachAsync.js:14:15)
  at nextWhenReady (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/node-type-emitter.js:55:29)
  at Object.emitSingleEvents [as emitNodeType] (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/node-type-emitter.js:60:5)
  at Walker._wLstatHandler (/Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:88:19)
  at /Users/shanetomlinson/development/fxa/packages/fxa-content-server/node_modules/walk/lib/walk.js:106:12
  at FSReqWrap.oncomplete (fs.js:154:5)

Fatal error: Unexpected token (107:12)


Execution Time (2019-08-05 12:10:51 UTC+1)
loading tasks  809ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 12%
jsxextract      5.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 86%
Total 6.5s

➜  fxa-content-server git:(master)
```

**Comment by shane-tomlinson** [comment]
This is caused by [this line](https://github.com/mozilla/fxa/blob/27310ca71d9c10c51ccd86126c4f060121d05ca4/packages/fxa-content-server/server/lib/routes/get-index.js#L107):

```js
          {
            ...configForFrontEnd,
            isPromptNoneEnabled: PROMPT_NONE_ENABLED,
            isPromptNoneEnabledForClient,
          }
```

If I change the spread operator to use Object.assign, no problems.

**Comment by philbooth** [comment]
> This is caused by [this line](https://github.com/mozilla/fxa/blob/27310ca71d9c10c51ccd86126c4f060121d05ca4/packages/fxa-content-server/server/lib/routes/get-index.js#L107):
>
> ```js
>           {
>             ...configForFrontEnd,
>             isPromptNoneEnabled: PROMPT_NONE_ENABLED,
>             isPromptNoneEnabledForClient,
>           }
> ```

If I change the spread operator to use Object.assign, no problems.

Could also do what I did for the auth server last week, and pass a flag to parse modern JS in jsxgettext:

https://github.com/mozilla/fxa/blob/adc66e75c14263397af4784554f2e79fa04f21f3/packages/fxa-auth-server/grunttasks/l10n-extract.js#L76
