### ISSUE TITLE
[content server] Intermittently Failing Functional Test: "cached signin - sign in with incorrect email case before normalization fix, on second attempt canonical form is used"

### ISSUE THREAD

**Issue by chenba** [mozilla/fxa#2232]
```
× firefox on linux 4.4.0-18362-Microsoft - cached signin - sign in with incorrect email case before normalization fix, on second attempt canonical form is used (10.92s)
    AssertionError: expected 'sync0.33307960879010756@restmail.net' to equal 'SYNC0.33307960879010756@RESTMAIL.NET'

    A sync0.33307960879010756@restmail.net
    E SYNC0.33307960879010756@RESTMAIL.NET

      at Command.<anonymous> @ tests/functional/lib/helpers.js:1970:14
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1969:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.sign in with incorrect email case before normalization fix, on second attempt canonical form is used [as test] @ tests/functional/sign_in_cached.js:99:12
      @ src/lib/Test.ts:263:51
```

**Comment by chenba** [comment]
Haven't seen this in a while.  Closing.
