### ISSUE TITLE
Generic error with initializeInterTabChannel

### ISSUE THREAD

**Issue by clouserw** [mozilla/fxa#2347]
This started happening after the last release.

https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6177303/

```
SecurityError: The operation is insecure.
  at Ne (/bundle-0e0b608a229f062397f52e26c9ab18413e0111c4/app.bundle.en.js:9:396475)
  at initializeInterTabChannel (/bundle-0e0b608a229f062397f52e26c9ab18413e0111c4/app.bundle.en.js:9:482279)
  at initializeDeps/< (/bundle-0e0b608a229f062397f52e26c9ab18413e0111c4/app.bundle.en.js:9:482566)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-307)
┆Issue Number: FXA-307

**Comment by shane-tomlinson** [comment]
This happens if the user has cookies disabled, BroadcastChannel is not available.

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

this is out of date
