### ISSUE TITLE
[Sentry]: TypeError: Cannot read property 'setItem' of null

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#2468]
https://sentry.prod.mozaws.net/operations/fxa-content-stage/issues/5337729/

```
TypeError: Cannot read property 'setItem' of null
  at Function.e.testStorage (/bundle-17133faa21d5bf76f9994269394364d67ff5ad02/app.bundle.en.js:1:66629)
  at Function.e.testLocalStorage (/bundle-17133faa21d5bf76f9994269394364d67ff5ad02/app.bundle.en.js:1:66836)
  at None (/bundle-17133faa21d5bf76f9994269394364d67ff5ad02/app.bundle.en.js:9:503325)
```

**Comment by clouserw** [comment]
We'll close this until/if we see it in production.
