### ISSUE TITLE
Move to SubHub QA environment

### ISSUE THREAD

**Issue by marty331** [mozilla/fxa#2507]
Please point FxA dev and stage to the new SubHub QA environment - 
https://qa.fxa.mozilla-subhub.app

**Comment by jrgm** [comment]
This has been on stage a while now, but with subhub_url changed to the above and subhub_key changed to the value I got from @marty331, and stage running the `latest` fxa-auth docker image, I get errors on calls to subscriptions/plans (and /customer) - `Authorization header requires 'Credential' parameter...`

**Comment by jrgm** [comment]
Longer error message:
```
Error: Authorization header requires 'Credential' parameter. Authorization header requires 
'Signature' parameter. Authorization header requires 'Si\
gnedHeaders' parameter. Authorization header requires existence of either``` a 'X-Amz-Date' or a
 'Date' header. Authorization=sh_...the-new-thing..\
.                                                                                                                                                   
                                                                                                                                                    
    at handleResponse (/app/lib/pool.js:71:21)                                                                                                      
    at RequestSet.callback (/app/node_modules/poolee/lib/pool.js:151:4)                                                                             
    at RequestSet.handleResponse (/app/node_modules/poolee/lib/request_set.js:66:8)                                                                 
    at Endpoint.complete (/app/node_modules/poolee/lib/endpoint.js:162:11)                                                                          
    at Endpoint.succeeded (/app/node_modules/poolee/lib/endpoint.js:168:8)                                                                          
    at IncomingMessage.gotEnd (/app/node_modules/poolee/lib/endpoint.js:326:8)                                                                      
    at IncomingMessage.emit (events.js:203:15)                                                                                                      
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)                                                                                         
    at endReadableNT (_stream_readable.js:1145:12)                                                                                                  
    at process._tickCallback (internal/process/next_tick.js:63:19)"}}
```

**Comment by jrgm** [comment]
@marty331 fixed one issue with authn to subhub, but there is still an error on posting to create the subscriptions. I've returned fxa stage to its prior state, and we can try again Monday.

**Comment by jrgm** [comment]
This is done for stage

**Comment by jrgm** [comment]
Closing
