### ISSUE TITLE
Intermittent auth-server test failure

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#2755]
Noticed this while implementing oauth->auth phase 2. Looks like it might just be a sorting issue.

```
  1) attached clients listing
       correctly lists a variety of attached clients:
     AssertionError: expected null to equal 'b661d24f7aab842c4f06c1d8754594dcd381f80c0debeccc501b7afc6fabeadb'
      at Context.it (test/remote/attached_clients_tests.js:98:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Fails:

```js
[ { clientId: '3c49430b43dfba77',
    deviceId: '999f67b8d8a7fc2af42c198d5632954e',
    sessionTokenId: null,
    refreshTokenId:
     'c03f94749c3ff980594546d70baec2183d9dc640480d3f479b465ae3361b04d3',
    isCurrentSession: false,
    deviceType: 'mobile',
    name: 'test device',
    createdTime: 1570228452832,
    lastAccessTime: 1570228452852,
    scope: [ 'https://identity.mozilla.com/apps/oldsync', 'profile' ],
    location: {},
    userAgent: '',
    os: null,
    createdTimeFormatted: 'a few seconds ago',
    lastAccessTimeFormatted: 'a few seconds ago' },
  { clientId: null,
    deviceId: 'd21f3dbf13a1e773eb41224f129ec4c1',
    sessionTokenId:
     'b661d24f7aab842c4f06c1d8754594dcd381f80c0debeccc501b7afc6fabeadb',
    refreshTokenId: null,
    isCurrentSession: true,
    deviceType: 'mobile',
    name: 'test device 🍓🔥在𝌆',
    createdTime: 1570228452624,
    lastAccessTime: 1570228452801,
    scope: null,
    location: {},
    userAgent: '',
    os: null,
    createdTimeFormatted: 'a few seconds ago',
    lastAccessTimeFormatted: 'a few seconds ago' } ]
```

Succeeds:

```js
[ { clientId: null,
    deviceId: '31d936c48c5bdbce2691b5fb6ae48096',
    sessionTokenId:
     '1362edf373014e6ce7803d6176068f5e53d43ec772114cfffe5a3b3b7f7598c0',
    refreshTokenId: null,
    isCurrentSession: true,
    deviceType: 'mobile',
    name: 'test device 🍓🔥在𝌆',
    createdTime: 1570228673248,
    lastAccessTime: 1570228673415,
    scope: null,
    location: {},
    userAgent: '',
    os: null,
    createdTimeFormatted: 'a few seconds ago',
    lastAccessTimeFormatted: 'a few seconds ago' },
  { clientId: '3c49430b43dfba77',
    deviceId: 'ad5fb4aa4a6c8ba7e84b356de52ebc98',
    sessionTokenId: null,
    refreshTokenId:
     'ea08cd0c0d1b338eebdcdbc364680c5facbb16d613e192690a62b2ec31f6292e',
    isCurrentSession: false,
    deviceType: 'mobile',
    name: 'test device',
    createdTime: 1570228673442,
    lastAccessTime: 1570228673461,
    scope: [ 'https://identity.mozilla.com/apps/oldsync', 'profile' ],
    location: {},
    userAgent: '',
    os: null,
    createdTimeFormatted: 'a few seconds ago',
    lastAccessTimeFormatted: 'a few seconds ago' } ]
```

**Comment by dannycoates** [comment]
I think I fixed this
