### ISSUE TITLE
Flakey CI tests

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#2822]
https://circleci.com/gh/mozilla/fxa/89967#tests/containers/1

```
Suite firefox on linux 4.15.0-1043-aws - complete_sign_in FAILED
Error: ElementNotVisible - input[type=email]
  at Command.<anonymous> @ tests/functional/lib/helpers.js:177:15
  at Command.<anonymous> @ tests/functional/lib/helpers.js:175:6
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:208:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:210:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:308:6
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:1520:6
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Suite.beforeEach @ tests/functional/complete_sign_in.js:49:8
  @ src/lib/Suite.ts:430:26
  at runLifecycleMethod @ src/lib/Suite.ts:398:13
  at next @ src/lib/Suite.ts:569:32
```

https://circleci.com/gh/mozilla/fxa/89801#tests/containers/3

```
Suite firefox on linux 4.15.0-1043-aws - oauth choose redirect FAILED
Error: ElementNotVisible - .ready .signup
  at Command.<anonymous> @ tests/functional/lib/helpers.js:177:15
  at Command.<anonymous> @ tests/functional/lib/helpers.js:175:6
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:208:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:210:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:1457:8
  at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
  at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
  at Suite.beforeEach @ tests/functional/oauth_choose_redirect.js:35:8
  @ src/lib/Suite.ts:430:26
  at runLifecycleMethod @ src/lib/Suite.ts:398:13
  at next @ src/lib/Suite.ts:569:32
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-423)
┆Issue Number: FXA-423

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Closing in favor of fxa-1852
