### ISSUE TITLE
Error: accountData cannot be set on an Account

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3042]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/6328713/

```
Error: accountData cannot be set on an Account
  at apply (./views/settings/change_password.jsx:270:12)
  at startApp (./app.js:14:12)
  at startApp (./app.js:14:12)
  at startApp (./app.js:14:12)
  at _updateUserFromBrowserAccount/< (./app.js:14:12)
...
(4 additional frame(s) were not displayed)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-469)
┆Issue Number: FXA-469

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

This page doesn't exist anymore
