### ISSUE TITLE
Error: Invalid OAuth parameter: scope

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3253]
https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/347483/

```
Error: Invalid OAuth parameter: scope
  at toError (./lib/errors.js:122:43)
  at toInvalidParameterError (./lib/errors.js:167:20)
  at string (./lib/transform.js:36:20)
  at _setupOAuthRPInfo (./models/reliers/browser.js:23:16)
  at None (./models/reliers/pairing/supplicant.js:59:19)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-517)
┆Issue Number: FXA-517

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

We've lost the sentry history that included this error. Closing
