### ISSUE TITLE
settings_common functional tests are not run

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa#3280]
The functional tests in the content server's /tests/functional/settings_common.js are not run because the [suites are incorrectly registered](https://github.com/mozilla/fxa/blob/4cf9f7cfbf81bf7c46ed54461ad741c8337a36f7/packages/fxa-content-server/tests/functional/settings_common.js#L157). The suites register the `<suitename>.test` rather than just `<suitename>`.

And above, the tests are added to the suite directly rather than to the `<suite>.tests` property.

**Comment by shane-tomlinson** [comment]
And when I fix them, it points out either the tests are broken or the code is. The user has cached credentials when hitting this: https://github.com/mozilla/fxa/blob/4cf9f7cfbf81bf7c46ed54461ad741c8337a36f7/packages/fxa-content-server/tests/functional/settings_common.js#L134

```
firefox on mac 18.7.0 - settings common - visit settings with a known uid does not redirect (21.073s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/93a339b6-795e-274c-b943-29d3df31e402/element / {"using":"css selector","value":"input[type=email]"}] Unable to locate element: input[type=email]
    For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'stomlinson-30887', ip: '192.168.1.229', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '9.0.1'
    Driver info: driver.version: unknown
      at Command.<anonymous> @ tests/functional/lib/helpers.js:205:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:210:8
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:75:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:308:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:1523:6
      at Command.<anonymous> @ tests/functional/lib/helpers.js:61:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:69:10
      at Test.suite.(anonymous function) [as test] @ tests/functional/settings_common.js:134:10
      @ src/lib/Test.ts:263:51
```
