### ISSUE TITLE
mkdirp should not be a devDependency of profile-server

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa#3491]
After an 'npm install --production' the profile-server does not start because modules mkdirp are missing (Dockerimage). npm install mkdirp' solves the problem.

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/fxa/packages/fxa-profile-server/scripts/run_dev.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fxa-profile-server@1.150.7 start: `scripts/run_dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-profile-server@1.150.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fxa/.npm/_logs/2019-11-23T12_17_23_015Z-debug.log

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-581)
┆Issue Number: FXA-581

**Comment by misterhsp** [comment]
The problem still exists and I mention again. mkdirp should not be a devDependency.
without module mkdir my docker image does not work. see log above.

thanks

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Thank you for filing this issue. This is not currently on our roadmap, and in an effort to focus our work, we are closing old issues that we are unlikely to be closed in the future. Thanks again.
