### ISSUE TITLE
QR-code-related failures in test-content-server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/fxa#3516]
[I'll sometimes see failures in the pairing tests related to QR codes.](https://circleci.com/gh/mozilla/fxa/121892#tests/containers/5)

These tend to go away with a test re-run. This time I peeked at the screenshot saved with the failure and noticed that it was still in the process of loading. Maybe these tests just aren't waiting long enough?

```
‣ Created remote session firefox on linux 4.15.0-1052-aws (08c1d45b-af64-4de5-8eea-d17ebb15086a)
Screenshot saved at: https://screencap.co.uk/images/275ccad081dd8851184f6df6fd40839b671392ec.png
× firefox on linux 4.15.0-1052-aws - pairing - it can pair (12.125s)
    Error: QRTimeout: No QR code found
      at getQrData.then.catch.err @ tests/functional/pairing.js:93:37
      at pollForScreenshot @ tests/functional/pairing.js:79:8
      at Timeout._onTimeout @ tests/functional/pairing.js:97:19
      at ontimeout @ timers.js:436:11
      at tryOnTimeout @ timers.js:300:5
      at listOnTimeout @ timers.js:263:5
      at Timer.processTimers @ timers.js:223:10
      at pollForScreenshot @ tests/functional/pairing.js:79:8
      at Timeout._onTimeout @ tests/functional/pairing.js:97:19
      at ontimeout @ timers.js:436:11
      at tryOnTimeout @ timers.js:300:5
      at listOnTimeout @ timers.js:263:5
      at Timer.processTimers @ timers.js:223:10
      at pollForScreenshot @ tests/functional/pairing.js:79:8
      at Command.<anonymous> @ tests/functional/pairing.js:105:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:62:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:76:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:70:10
      at Test.it can pair [as test] @ tests/functional/pairing.js:143:12
      @ src/lib/Test.ts:263:51
      at Test.it can pair [as test] @ tests/functional/pairing.js:147:17
      @ src/lib/Test.ts:263:51
      at Test.it can pair [as test] @ tests/functional/pairing.js:202:17
      @ src/lib/Test.ts:263:51
```

![275ccad081dd8851184f6df6fd40839b671392ec](https://user-images.githubusercontent.com/21687/69759514-27ed3b00-1117-11ea-9680-3917eea140e8.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-585)
┆Issue Number: FXA-585

**Comment by vladikoff** [comment]
yeah, we can possibly increase the timeout for the qr code to show up

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

This seems to have been fixed a while ago. We can reopen if it happens again
