### ISSUE TITLE
profile-server docker image is being a jerk

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#3754]
```
Step 8/26 : RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/v3.9/community/ --no-cache graphicsmagick=1.3.31-r0 git &&     apk add --repository http://dl-cdn.alpinelinux.org/alpine/v3.9/community/ --no-cache --virtual .build-deps git python make g++
 ---> Running in 36189b4ebcd6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libjasper.so.4 (missing):
    required by: graphicsmagick-1.3.31-r0[so:libjasper.so.4]
The command '/bin/sh -c apk add --repository http://dl-cdn.alpinelinux.org/alpine/v3.9/community/ --no-cache graphicsmagick=1.3.31-r0 git &&     apk add --repository http://dl-cdn.alpinelinux.org/alpine/v3.9/community/ --no-cache --virtual .build-deps git python make g++' returned a non-zero code: 2

Exited with code exit status 2
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-847)
┆Priority: Medium
┆Issue Number: FXA-847

**Comment by dannycoates** [comment]
Also, the current docker image on docker hub throws this on start up

```
Error: Cannot find module 'convict'
Require stack:
- /app/lib/config.js
- /app/bin/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/lib/config.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/config.js', '/app/bin/server.js' ]
}
```
