### ISSUE TITLE
redis error seen in stage

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4395]
I was looking at the auth-server for an unrelated issue with Ben and happened to see this stack get dumped. (I don't see this error on Sentry though).

/cc @dannycoates 

```
{"error":"TypeError: Cannot read property 'clientId' of null","stack":"
    at Function.parse (/app/lib/oauth/db/accessToken.js:102:24)
    at FxaRedis.getAccessToken (/app/lib/redis.js:87:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OauthDB.getAccessToken (/app/lib/oauth/db/index.js:77:15)
    at async Object.verify (/app/lib/oauth/token.js:41:17)
    at async verify (/app/lib/oauth/routes/verify.js:34:18)
    at async module.exports.internals.Manager.execute (/app/node_modules/hapi/lib/toolkit.js:35:28)
    at async Object.internals.handler (/app/node_modules/hapi/lib/handler.js:50:20)
    at async exports.execute (/app/node_modules/hapi/lib/handler.js:35:20)
    at async Request._lifecycle (/app/node_modules/hapi/lib/request.js:265:32)
    at async Request._execute (/app/node_modules/hapi/lib/request.js:170:9)"}}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1281)
┆Issue Number: FXA-1281

**Comment by dannycoates** [comment]
This happens when redis doesn't have the token and is caught [here](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/redis.js#L90). It'll happen a lot at first. I'll change it to check for null in the next release instead of letting it error.
