### ISSUE TITLE
[stage][162] event-broker: Error: Cannot find module 'uuid'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4538]
Fails to start on below, probably https://github.com/mozilla/fxa/pull/4479
```
Error: Cannot find module 'uuid'
Require stack:
- /app/dist/lib/jwts.js
- /app/dist/lib/api/index.js
- /app/dist/lib/proxy-server.js
- /app/dist/bin/worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/dist/lib/jwts.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/dist/lib/api/index.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/lib/jwts.js',
    '/app/dist/lib/api/index.js',
    '/app/dist/lib/proxy-server.js',
    '/app/dist/bin/worker.js'
  ]
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1368)
┆Issue Number: FXA-1368

**Comment by jrgm** [comment]
Ah. `uuid` is a devDependency in package.json, but it's not really.

**Comment by jrgm** [comment]
```
$ docker run -it --rm mozilla/fxa-event-broker:v1.162.0 \
        sh -c 'find node_modules -name uuid\* -type d'
node_modules/request/node_modules/uuid
node_modules/aws-sdk/node_modules/uuid
$$
```

**Comment by jrgm** [comment]
Hmm. I pulled the latest build of fxa master branch, which has the change from #4540 

However, the build of the `latest` image is not on current HEAD of master. And the uuid module has not been added.

```
$ docker run -it --rm mozilla/fxa-event-broker:latest \
       sh -c 'find node_modules -name uuid\* -type d'
node_modules/request/node_modules/uuid
node_modules/aws-sdk/node_modules/uuid
$ docker run -it --rm mozilla/fxa-event-broker:latest sh -c 'cat version.json'
{"version":{"hash":"d7517edd5875afeabe9bd56d5f9eb3348e3f8148","version":"master",
"source":"https://github.com/mozilla/fxa","build":"https://circleci.com/gh/mozilla/fxa/159869"}}
$ 
```
Would making a whitespace change to a `ts` force that image to be recreated?

**Comment by jrgm** [comment]
Ah. The deploy job failed on:
```
Step 5/14 : RUN npm run build
 ---> Running in f4aacf25c858

> fxa-admin-server@1.154.0 build /app
> ./node_modules/typescript/bin/tsc

node_modules/apollo-cache-control/dist/index.d.ts(24,9): error TS2717: Subsequent property declarations must have the same type.  Property 'cacheControl' must be of type '{ setCacheHint: (hint: CacheHint) => void; cacheHint: CacheHint; }', but here has type '{ setCacheHint: (hint: CacheHint) => void; cacheHint: CacheHint; }'.
```
https://circleci.com/gh/mozilla/fxa/159896

I'd hit that locally but assumed it was just something about my build setup.

**Comment by jrgm** [comment]
Re-closing since it appears that the admin-panel issue doesn't affect train-162
