### ISSUE TITLE
[prod][train-164] profile exceptions

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#4691]
```
"stack":"TypeError: Cannot read property 'profileChangedAt' of undefined
    at /app/lib/routes/profile.js:94:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports.internals.Manager.execute (/app/node_modules/@hapi/hapi/lib/toolkit.js:31:28)
    at async Object.internals.handler (/app/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/app/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/app/node_modules/@hapi/hapi/lib/request.js:261:32)
    at async Request._execute (/app/node_modules/@hapi/hapi/lib/request.js:166:9)"}}
```
Looking back, this error happens in stage too, so I'm not clear on why things nominally "work" for testing.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1442)
┆Issue Number: FXA-1442

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~vfilippov@mozilla.com] is this fixed?
