### ISSUE TITLE
[train-168] support panel fails on startup on missing dependency

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5085]
I tried putting `master` in stage, and support panel fails to start on:
```
internal/modules/cjs/loader.js:983
throw err;
^
Error: Cannot find module 'semver'
Require stack:
- /app/node_modules/useragent/features/index.js
- /app/node_modules/@hapi/scooter/lib/index.js
- /app/dist/lib/server.js
- /app/dist/bin/worker.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
at Function.Module._load (internal/modules/cjs/loader.js:862:27)
at Module.require (internal/modules/cjs/loader.js:1042:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object.<anonymous> (/app/node_modules/useragent/features/index.js:7:14)
at Module._compile (internal/modules/cjs/loader.js:1156:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
at Module.load (internal/modules/cjs/loader.js:1000:32)
at Function.Module._load (internal/modules/cjs/loader.js:899:14)
at Module.require (internal/modules/cjs/loader.js:1042:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/app/node_modules/useragent/features/index.js',
'/app/node_modules/@hapi/scooter/lib/index.js',
'/app/dist/lib/server.js',
'/app/dist/bin/worker.js'
]
}
docker-fxa-support-panel.service: main process exited, code=exited, status=1/FAILURE
```
This may be an issue with the useragent package since `semver` is listed as a `devDependency` but it is required on starting - https://github.com/3rd-Eden/useragent/blob/master/package.json#L35-L56 and https://github.com/3rd-Eden/useragent/blob/master/features/index.js#L7

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1746)
┆Issue Number: FXA-1746

**Comment by dannycoates** [comment]
I was wondering if one would fail because of a devDependency...

**Comment by jrgm** [comment]
There's nothing, aside from the docker changes, in 168 for fxa-support-panel, so I can skip this release for support-panel to allow time to get a fix for this issue.

**Comment by jrgm** [comment]
I guess a workaround would be to have fxa-support-panel directly depend on `semver`.

**Comment by dannycoates** [comment]
perhaps by coincidence updating `@hapi/scooter` to 6.0.0 also fixes it, but that seems fragile. IDK why npm hoisted `useragent` to the top, but left `semver` under `@hapi/scooter/node_modules` 🤷‍♂️

lets add `semver` to deps
