### ISSUE TITLE
[Dockerfile]  fxa-profile-server dockerfile not working at v1.169.0

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/fxa#5194]
This problem is introduced in 4dd0b0007

fxa-profile-server needs `graphicsmagick` but the Dockerfile is replaced with a common dockerfile which do not install  `graphicsmagick`.

Temp solution: `docker exec -u root  fxa-profile-server  sh -c "apt update -y -qq && apt install  graphicsmagick -y -qq"`

Error Log:
```
{"Timestamp":1588576455289000000,"Logger":"fxa-profile-server","Type":"compute.image-cc.compute","Severity":2,"Pid":13,"EnvVersion":"2.0","Fields":
{"error":"Error: write EPIPE","stack":"
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:784:11)
    at Socket._write (net.js:796:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at gm._spawn (/app/node_modules/gm-reloaded/lib/command.js:253:18)
    at gm._exec (/app/node_modules/gm-reloaded/lib/command.js:190:17)
    at gm.identify (/app/node_modules/gm-reloaded/lib/getters.js:127:10)
    at /app/lib/compute/image-cc.js:26:15
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:77:14)
    at processImage (/app/lib/compute/image-cc.js:17:10)
    at compute (/app/lib/compute/image-cc.js:68:3)"}}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1815)
┆Issue Number: FXA-1815

**Comment by jackyzy823** [comment]
The same issue as #5196
