### ISSUE TITLE
Non-test error in auth-server tests

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa#5226]
https://github.com/mozilla/fxa/pull/5056 introduced this error to the `local` tests of auth-server.

It appears this is somehow relate to `ts-node/register` and the `--recursive` mocha option because when running each test file individually this error doesn't occur.

```sh
Unhandled rejection Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql/lib/Connection.js:419:13)
    at Object.onceWrapper (events.js:416:28)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
    --------------------
    at Protocol._enqueue (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql/lib/Connection.js:130:18)
    at Patcher.createConnection (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/index.js:122:19)
    at /Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:607:21
    at /Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:246:17
    at iterate (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/node_modules/async/lib/async.js:605:19)
    at Patcher.connect (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mysql-patcher/index.js:64:9)
    at Patcher.tryCatcher (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:11:39)
    at Function.mysqlConnect [as connect] (/Users/dcoates/code/fxa/packages/fxa-auth-server/lib/oauth/db/mysql/index.js:105:60)
    at new OauthDB (/Users/dcoates/code/fxa/packages/fxa-auth-server/lib/oauth/db/index.js:28:24)
    at Object.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/lib/oauth/db/index.js:268:18)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:839:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/lib/oauth/routes/client/get.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:839:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/lib/oauth/routes/index.js:23:13)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:839:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/lib/oauthdb/index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:839:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.mockOAuthDB (/Users/dcoates/code/fxa/packages/fxa-auth-server/test/mocks.js:557:5)
    at makeRoutes (/Users/dcoates/code/fxa/packages/fxa-auth-server/test/local/routes/devices-and-sessions.js:44:44)
    at Suite.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/test/local/routes/devices-and-sessions.js:356:25)
    at Object.create (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at Object.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/test/local/routes/devices-and-sessions.js:325:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Module.m._compile (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:839:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/ts-node/src/index.ts:842:12)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/dcoates/code/fxa/packages/fxa-auth-server/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1833)
┆Issue Number: FXA-1833

**Comment by jodyheavener** [comment]
@dannycoates I've discovered (and am [still discovering](https://github.com/mozilla/fxa/pull/5161)) using ts-node in mocha tests is leading to crazy timeouts all over. My guess is it has to do with ts-node needing to consume and compile everything each time.
