### ISSUE TITLE
Delete account script is not working

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa#6704]
When I attempt to run the delete-account script in fxa-auth-server I get the following error: `ERROR: no database connection available for a query. You need to bind the model class or the query to a knex instance.`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2624)
┆Issue Number: FXA-2624

**Comment by dannycoates** [comment]
🤦

**Comment by jbuck** [comment]
Now with an actual stack trace:

```
ERROR: Error: no database connection available for a query. You need to bind the model class or the query to a knex instance.
    at QueryBuilder.knex (/fxa/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:206:15)
    at buildKnexQuery (/fxa/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1591:56)
    at doExecute (/fxa/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1482:31)
    at QueryBuilder.execute (/fxa/node_modules/objection/lib/queryBuilder/QueryBuilder.js:684:28)
    at async StripeHelper.removeCustomer (/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/payments/stripe.js:371:26)
    at async Object.accountDestroy [as handler] (/fxa/packages/fxa-auth-server/dist/fxa-auth-server/lib/routes/account.js:1403:13)
```

@dannycoates believes this is because the new DB config isn't being passed to the stripe helper correctly
