### ISSUE TITLE
`latest.dev.lcip.org`: content-server has no content

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#729]
On latest.dev.lcip.org, from command line, `docker logs -f content`, I get:

{"Timestamp":1554352803026000000,"Logger":"fxa-content-server","Type":"routes.index.featureFlags.error","Severity":2,"Pid":8,"EnvVersion":"2.0","Fields":{"error":"TimeoutError: ResourceRequest timed out","stack":"\n    at ResourceRequest._fireTimeout (/app/node_modules/generic-pool/lib/ResourceRequest.js:62:17)\n    at Timeout.bound (/app/node_modules/generic-pool/lib/ResourceRequest.js:8:15)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}}
{"Timestamp":1554352803026000000,"Logger":"fxa-content-server","Type":"route.500.Error: Failed to lookup view \"en/index\" in views directory \"/app/server/templates/pages/dist\"","Severity":2,"Pid":8,"EnvVersion":"2.0","Fields":{"stack":"\n    at Function.render (/app/node_modules/express/lib/application.js:580:17)\n    at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)\n    at ServerResponse.res.render (/app/server/lib/localized-render.js:34:24)\n    at process (/app/server/lib/routes/get-index.js:79:11)"}}
Error: Failed to lookup view "en/500" in views directory "/app/server/templates/pages/dist"
    at Function.render (/app/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)
    at ServerResponse.res.render (/app/server/lib/localized-render.js:34:24)
    at module.exports (/app/server/lib/500.js:16:16)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/celebrate/lib/index.js:124:12
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at app.use (/app/server/bin/fxa-content-server.js:192:5)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at ravenErrorMiddleware (/app/node_modules/raven/lib/client.js:560:14)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at app.use (/app/server/bin/fxa-content-server.js:175:7)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/celebrate/lib/index.js:124:12
    at app.use (/app/server/lib/routes.js:123:7)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/app/node_modules/express/lib/router/index.js:275:10)
    at done (/app/node_modules/express/lib/response.js:1003:25)
    at Function.render (/app/node_modules/express/lib/application.js:582:14)
    at ServerResponse.render (/app/node_modules/express/lib/response.js:1008:7)
    at ServerResponse.res.render (/app/server/lib/localized-render.js:34:24)
    at process (/app/server/lib/routes/get-index.js:79:11)

**Comment by jrgm** [comment]
Versions:

[
  {
    "commit": "531b21cbb9be024e379cdd141a6ddd1f4e58ad91",
    "version": "1.134.0",
    "l10n": "ed2420980d52e103b24299125a3c44b231f904e2",
    "source": "https://github.com/mozilla/fxa",
    "url": "https://latest.dev.lcip.org/__version__?env=latest"
  },
  {
    "version": "1.134.0",
    "commit": "531b21cbb9be024e379cdd141a6ddd1f4e58ad91",
    "source": "https://github.com/mozilla/fxa",
    "url": "https://latest.dev.lcip.org/auth/__version__?env=latest"
  },
  {
    "version": "1.134.0",
    "commit": "531b21cbb9be024e379cdd141a6ddd1f4e58ad91",
    "source": "https://github.com/mozilla/fxa",
    "url": "https://oauth-latest.dev.lcip.org/__version__?env=latest"
  },
  {
    "version": "1.133.0",
    "commit": "531b21cbb9be024e379cdd141a6ddd1f4e58ad91",
    "source": "https://github.com/mozilla/fxa",
    "url": "https://latest.dev.lcip.org/profile/__version__?env=latest"
  }
]

**Comment by jrgm** [comment]
There's nothing in /app/server/templates/pages/dist inside the content container on `latest.dev.lcip.org`.

```
# docker exec -it content sh
~ $ 
~ $ 
~ $ ls -l /app/server/templates/pages/dist
total 0
~ $ ls -l /app/server/templates/pages
total 8
drwxr-xr-x    1 root     root          4096 Apr  4 02:25 dist
drwxr-xr-x    2 root     root          4096 Apr  4 01:57 src
~ $ ls -l /app/server/templates/pages/src
total 44
-rw-r--r--    1 root     root          1428 Apr  4 01:57 404.html
-rw-r--r--    1 root     root          1383 Apr  4 01:57 500.html
-rw-r--r--    1 root     root          1383 Apr  4 01:57 502.html
-rw-r--r--    1 root     root          1439 Apr  4 01:57 503.html
-rw-r--r--    1 root     root          4411 Apr  4 01:57 index.html
-rw-r--r--    1 root     root          1200 Apr  4 01:57 mocha.html
-rw-r--r--    1 root     root          1263 Apr  4 01:57 privacy.html
-rw-r--r--    1 root     root          1327 Apr  4 01:57 style-guide.html
-rw-r--r--    1 root     root          1266 Apr  4 01:57 terms.html
-rw-r--r--    1 root     root          1738 Apr  4 01:57 update_firefox.html
~ $ ls -l /app/server/templates
total 4
drwxr-xr-x    1 root     root          4096 Apr  4 02:25 pages
~ $ ls -l /app/server
total 16
drwxr-xr-x    2 root     root          4096 Apr  4 01:57 bin
drwxr-xr-x    2 root     root          4096 Apr  4 01:58 config
drwxr-xr-x    5 root     root          4096 Apr  4 01:57 lib
drwxr-xr-x    1 root     root          4096 Apr  4 02:25 templates
```

**Comment by shane-tomlinson** [comment]
cc @dannycoates and @philbooth

**Comment by philbooth** [comment]
@shane-tomlinson, is `/app/server/templates/pages/dist` generated by `npm run build-production`?

Do we know whether that command is failing for some reason?

**Comment by shane-tomlinson** [comment]
@philbooth - empty

**Comment by philbooth** [comment]
Sorry, not sure I made myself clear.

I mean is it *supposed to be* generated by `npm run build-production`

**Comment by philbooth** [comment]
(the natural follow-up question being, can we see the output from `npm run build-production` on the box?)

**Comment by jrgm** [comment]
> can we see the output from npm run build-production on the box?

```
[ec2-user@ip-172-31-44-86 ~]$ docker exec -it content sh

~ $ npm run build-production --unsafe-perm
npm run build-production --unsafe-perm

> fxa-content-server@1.134.0 build-production /app
> NODE_ENV=production grunt build

Running "clean:app" (clean) task
>> 0 paths cleaned.

Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "clean:tos_pp" (clean) task
>> 0 paths cleaned.

Running "githash:main" (githash) task
>> Could not read git information: Error: Command failed: git describe --always --tag --abbrev=0
>> fatal: not a git repository (or any of the parent directories): .git
Unhandled rejection Error: Command failed: git describe --always --tag --abbrev=0
fatal: not a git repository (or any of the parent directories): .git

  at ChildProcess.exithandler (child_process.js:294:12)
  at ChildProcess.emit (events.js:189:13)
  at maybeClose (internal/child_process.js:970:16)
  at Socket.stream.socket.on (internal/child_process.js:389:11)
  at Socket.emit (events.js:189:13)
  at Pipe._handle.close (net.js:597:12)

~ $
```

**Comment by philbooth** [comment]
So I think the problem is that the Docker image contains just the `fxa-content-server` directory, outside the context of the monorepo. But `npm run build-production` needs to be in a git repo because it tries to read the commit hash.

So the fix should be to change the Dockerfile, having a look at that now...

**Comment by jrgm** [comment]
I did `git init; git add .; git commit -m init; npm run build-production --unsafe-perm` inside the container, and it appears so far, to have produced something that is passing functional tests.

Although, including the `.git` directory inside the docker image, which is what was done in the past (e.g., v1.133.0), strikes me as a bug.

**Comment by philbooth** [comment]
I wonder whether we really need the git hash. If we didn't it would stop us from needing any kind of hackery at all. The comment in `grunttasks/githash.js` says:

```js
// set up `githash.main.hash` for use in banner in the uglify task
```

@shane-tomlinson, @vladikoff, is there something else we can do to make uglify happy there, that doesn't require having a commit hash?

**Comment by jrgm** [comment]
The commit hash used to be visible in minimized content iirc, but I can't seem to see it now. I forget if this was for debugging purposes, or if it had a deeper purpose.

Is there a way we could pass in a git sha into the `docker build` execution via the environment, as a substitute for copying the whole `.git` directory into the docker image?

**Comment by vladikoff** [comment]
if we want a quick fix we can add an option to `fail: false` for now https://www.npmjs.com/package/grunt-githash#optionsfail

If there's no more git repo, then I think we would need to make more changes

**Comment by philbooth** [comment]
I experimented to see what would happen if I just deleted `githash` from the `grunttasks/build.js`.

Method:

1. `npm run build-production`
2. `cp -R dist ../../../dist-before`
3. `cp -R server/templates/pages/dist ../../../server-dist-before`
4. Delete `githash`
5. `npm run build-production`
6. `cp -R dist ../../../dist-after`
7. `cp -R server/templates/pages/dist ../../../server-dist-after`
8. Diff between the files in `-before` and the files in `-after`.

Result:

No differences.

Conclusion:

We can just delete the `githash` dependency and grunt task, right?

**Comment by shane-tomlinson** [comment]
The purpose of git-hash was to aid in auditing and verification. It was supposed to place the git hash in the top level comment on the main js bundle, but it looks like this broke a while ago. Curious users could look at the git hash and build for themselves, and compare the output to ensure it matches what we are serving. It looks like that broke along the way plus we put the git sha in https://accounts.firefox.com/__version__, so should be good here.
