### ISSUE TITLE
fxa-auth-server load-test: spawn ping ENOENT

### ISSUE THREAD

**Issue by enote-kane** [mozilla/fxa#7539]
## Description

When executing some load-testing against the fxa-auth-server, the following uncaught exception popped up and the node process just died:

```
Error: spawn ping ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
```

### Steps to reproduce

Unclear, but I used a 30-worker locust load-test scenario that was creating 1000 users (preVerified=true), each worker 1 user per second.

This happens when running in a docker-compose setup (single service node) as well as a multi-node Kubernetes setup.

### Expected result

All account create requests succeed.

### Actual result

The worst case I had, this has resulted in more than 30% of all account create requests to fail because of that (since the service restart may take some time):

```
 Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
 POST /v1/account/create                                         1000  326(32.60%)  |   36853      52   60037   32000  |    1.11    0.36
 GET /v1/account/keys                                             925     0(0.00%)  |     116      14    2058      67  |    1.03    0.00
 POST /v1/account/login                                          7925     0(0.00%)  |     594     242   43289     430  |    8.80    0.00
 POST /v1/account/login?keys=true                                 879     0(0.00%)  |     580     254    4203     430  |    0.98    0.00
 POST /v1/account/status                                         8531     2(0.02%)  |      38      10    2069      19  |    9.48    0.00
 POST /v1/introspect                                            77109     6(0.01%)  |      21       4     853      11  |   85.66    0.01
 POST /v1/oauth/destroy                                         28871     3(0.01%)  |      26       5     624      12  |   32.07    0.00
 POST /v1/oauth/token                                           68725     9(0.01%)  |     214      10   42486      76  |   76.34    0.01
 POST /v1/password/change/finish                                   46     0(0.00%)  |    1006     528    3809     790  |    0.05    0.00
 POST /v1/password/change/start                                    46     0(0.00%)  |     928     494    2085     760  |    0.05    0.00
 DELETE /v1/recoveryKey                                            29     0(0.00%)  |     199      19    1158      78  |    0.03    0.00
 POST /v1/recoveryKey                                              29     0(0.00%)  |     168      39     598      99  |    0.03    0.00
 GET /v1/recovery_email/status                                    674     3(0.45%)  |   17880      15   41798   11000  |    0.75    0.00
 POST /v1/session/destroy                                        8807     0(0.00%)  |     163      11   42439      64  |    9.78    0.00
 GET /v1/session/status                                         99488     0(0.00%)  |     156       5   42267      53  |  110.51    0.00
--------------------------------------------------------------------------------------------------------------------------------------------
 Aggregated                                                    303084   349(0.12%)  |     293       4   60037      52  |  336.68    0.39
```

### Environment

PyFxA / Python Requests

### Additional Log Data

The 20 log messages from before the crash:
```json
{"Timestamp":1613498907212000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"route./introspect.200","missingFlowId":true}}
{"Timestamp":1613498907473000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.f2a15970033d494ab6642daab22386e8@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907484000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.aabc06fff742429e9bb004d45d8349e6@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907564000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.55b2bd4095d748acb5fd5728665bb454@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907595000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.a0adaf40e6ed4640afa420344f522d7b@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907884000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.caba7344fd994dfa98a861987d9b630a@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907890000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.002de0ac92454b5ebda9b18cef23bc06@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907947000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.59acb5588c2d4e90bf735d60cfc58fc9@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498907979000000,"Logger":"fxa-auth-server","Type":"account.create.emptyLocale","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"email":"load-testing.bbf113fcd8d54cb39e7f789b8f8e9d82@mycorp.net","agent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1"}}
{"Timestamp":1613498908080000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"token.created","missingFlowId":true}}
{"Timestamp":1613498908085000000,"Logger":"fxa-auth-server","Type":"amplitudeEvent","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"op":"amplitudeEvent","event_type":"fxa_activity - access_token_created","time":1613498908080,"user_id":"d3134685720141b58904e1eda6acf18b","app_version":"197.3","language":"en","event_properties":"{\"service\":\"undefined_oauth\",\"oauth_client_id\":\"a6042952a8d09ca2\"}","user_properties":"{\"ua_browser\":\"Python Requests\",\"ua_version\":\"2.25\",\"$append\":{\"fxa_services_used\":\"undefined_oauth\"},\"sync_device_count\":0,\"sync_active_devices_day\":0,\"sync_active_devices_week\":0,\"sync_active_devices_month\":0}"}}
{"Timestamp":1613498908086000000,"Logger":"fxa-auth-server","Type":"activityEvent","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"oauth.token.created","userAgent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1","grantType":"fxa-credentials","uid":"d3134685720141b58904e1eda6acf18b","ecosystemAnonId":"null","clientId":"a6042952a8d09ca2","service":"a6042952a8d09ca2"}}
{"Timestamp":1613498908086000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"oauth.token.created","missingFlowId":true}}
{"Timestamp":1613498908086000000,"Logger":"fxa-auth-server","Type":"amplitudeEvent","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"op":"amplitudeEvent","event_type":"fxa_activity - oauth_access_token_created","time":1613498908086,"user_id":"d3134685720141b58904e1eda6acf18b","app_version":"197.3","language":"en","event_properties":"{\"service\":\"undefined_oauth\",\"oauth_client_id\":\"a6042952a8d09ca2\"}","user_properties":"{\"ua_browser\":\"Python Requests\",\"ua_version\":\"2.25\",\"$append\":{\"fxa_services_used\":\"undefined_oauth\"},\"sync_device_count\":0,\"sync_active_devices_day\":0,\"sync_active_devices_week\":0,\"sync_active_devices_month\":0}"}}
{"Timestamp":1613498908115000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"token.created","missingFlowId":true}}
{"Timestamp":1613498908120000000,"Logger":"fxa-auth-server","Type":"amplitudeEvent","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"op":"amplitudeEvent","event_type":"fxa_activity - access_token_created","time":1613498908115,"user_id":"764e91a80ede490fb29bc50da9653512","app_version":"197.3","language":"en","event_properties":"{\"service\":\"undefined_oauth\",\"oauth_client_id\":\"a6042952a8d09ca2\"}","user_properties":"{\"ua_browser\":\"Python Requests\",\"ua_version\":\"2.25\",\"$append\":{\"fxa_services_used\":\"undefined_oauth\"},\"sync_device_count\":0,\"sync_active_devices_day\":0,\"sync_active_devices_week\":0,\"sync_active_devices_month\":0}"}}
{"Timestamp":1613498908121000000,"Logger":"fxa-auth-server","Type":"activityEvent","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"oauth.token.created","userAgent":"Mozilla/5.0 (Mobile; Firefox Accounts; rv:1.0) PyFxA/0.7.7 python-requests/2.25.1","grantType":"fxa-credentials","uid":"764e91a80ede490fb29bc50da9653512","ecosystemAnonId":"null","clientId":"a6042952a8d09ca2","service":"a6042952a8d09ca2"}}
{"Timestamp":1613498908121000000,"Logger":"fxa-auth-server","Type":"metricsEvents.emitFlowEvent","Severity":2,"Pid":1,"EnvVersion":"2.0","Fields":{"event":"oauth.token.created","missingFlowId":true}}
{"Timestamp":1613498908122000000,"Logger":"fxa-auth-server","Type":"amplitudeEvent","Severity":6,"Pid":1,"EnvVersion":"2.0","Fields":{"op":"amplitudeEvent","event_type":"fxa_activity - oauth_access_token_created","time":1613498908121,"user_id":"764e91a80ede490fb29bc50da9653512","app_version":"197.3","language":"en","event_properties":"{\"service\":\"undefined_oauth\",\"oauth_client_id\":\"a6042952a8d09ca2\"}","user_properties":"{\"ua_browser\":\"Python Requests\",\"ua_version\":\"2.25\",\"$append\":{\"fxa_services_used\":\"undefined_oauth\"},\"sync_device_count\":0,\"sync_active_devices_day\":0,\"sync_active_devices_week\":0,\"sync_active_devices_month\":0}"}}
{"Timestamp":1613498908231000000,"Logger":"fxa-auth-server","Type":"uncaughtException","Severity":0,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"Error: spawn ping ENOENT","stack":"\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)\n    at onErrorNT (internal/child_process.js:465:16)\n    at processTicksAndRejections(internal/process/task_queues.js:80:21)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at listOnTimeout (internal/timers.js:523:9)\n    at processTimers (internal/timers.js:497:7)"}}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3046)
┆Issue Number: FXA-3046

**Comment by enote-kane** [comment]
Looks like a clear overload issue in some internals, since scaling to a 4-nodes setup and repeating the test didn't reveal the same in multiple test runs.

**Comment by enote-kane** [comment]
Just noticed the same issue in one of our Kubernetes clusters (but not in any others, though):
```
Error: spawn ping ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
...resulting into pods becoming unresponsive and being restarted.
