### ISSUE TITLE
Error: A suite or test named "Firefox Desktop Sync v1" has already been added

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#814]
I was running tests on teamcity with builds from the monorepo, and they were aborting with `Error: A suite or test named "Firefox Desktop Sync v1" has already been added`. 

I distinctly renamed the name in the three duplicate calls to `registerSuite('Firefox Desktop Sync v1')` and the tests worked. But I'll defer to someone else what those distinct names should be.

```
Error: A suite or test named "Firefox Desktop Sync v1" has already been added
  at <src/lib/Suite.ts:298:14>
  at Suite.add  <src/lib/Suite.ts:296:15>
  at <src/lib/interfaces/object.ts:203:11>
  at Node.addSuite  <src/lib/executors/Node.ts:184:27>
  at _registerSuite  <src/lib/interfaces/object.ts:190:11>
  at registerSuite  <src/lib/interfaces/object.ts:83:13>
  at Object.<anonymous>  <tests/functional/fx_firstrun_v1.js:24:1>
{ Error: A suite or test named "Firefox Desktop Sync v1" has already been added
    at /home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/node_modules/intern/lib/Suite.js:215:27
    at Array.forEach (<anonymous>)
    at Suite.add (/home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/node_modules/intern/lib/Suite.js:213:24)
    at /home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/node_modules/intern/lib/interfaces/object.js:96:20
    at Array.forEach (<anonymous>)
    at Node.addSuite (/home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/node_modules/intern/lib/executors/Node.js:162:37)
    at _registerSuite (/home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/node_modules/intern/lib/interfaces/object.js:88:18)
    at registerSuite (/home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/node_modules/intern/lib/interfaces/object.js:23:24)
    at Object.<anonymous> (/home/teamcity/agent/work/e4249c2d6a4e9e8d/fxa-stage/packages/fxa-content-server/tests/functional/fx_firstrun_v1.js:24:1)
    at Module._compile (module.js:653:30) reported: true }
Process exited with code 1
```

**Comment by jrgm** [comment]
Fixed in https://github.com/mozilla/fxa/pull/815
