### ISSUE TITLE
502 Bad Gateway,register and login is not working on AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/fxa#858]
STR:
1. Load AMO dev and try to register or login

Expected result:
register/login is done successfully

Actual result:
502 Bad Gateway in the Console - the page displays a red warning Unexpected error

Notes:
This is reproducible only on AMO dev - FF66(Wi10). The login works on the other AMO servers.

![502 error amo dev](https://user-images.githubusercontent.com/33448286/56286180-bf21f700-6121-11e9-822d-d96e0d2363e5.png)

**Comment by shane-tomlinson** [comment]
cc @jrgm, @jbuck

**Comment by vladikoff** [comment]
auth-server crashed with 

```
{"Timestamp":1555471065754000000,"Logger":"fxa-auth-server","Type":"uncaughtException","Severity":0,"Pid":6,"EnvVersion":"2.0","Fields":{"error":"Error: EMFILE: too many open files, uv_resident_set_memory","stack":"\n    at process.memoryUsage (internal/process/per_thread.js:136:5)\n    at Timeout.measure [as _onTimeout] (/app/node_modules/hapi/node_modules/heavy/lib/index.js:61:33)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}}
{"Timestamp":1555471065755000000,"Logger":"fxa-auth-server","Type":"Error: EMFILE: too many open files, uv_resident_set_memory","Severity":0,"Pid":6,"EnvVersion":"2.0","Fields":{"stack":"\n    at process.memoryUsage (internal/process/per_thread.js:136:5)\n    at Timeout.measure [as _onTimeout] (/app/node_modules/hapi/node_modules/heavy/lib/index.js:61:33)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}}
scripts/start-server.sh: exit: line 3: Illegal number: [0]
```

I restarted it and should be good for now

**Comment by ioanarusiczki** [comment]
@vladikoff Yes, it is no longer reproducible on AMO dev - FF66(Win10). 

![login works](https://user-images.githubusercontent.com/33448286/56345009-6c9b1600-61c7-11e9-9dc4-21169b535094.gif)
