### ISSUE TITLE
auth-server flaky test

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8962]
lib/cad-reminders create process removed second reminder from redis correctly - removed second reminder from redis correctly

https://app.circleci.com/pipelines/github/mozilla/fxa/13129/workflows/2881c192-9ebc-4317-ae9f-c542e5689b38/jobs/189835

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXA-2485)

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

I've been seeing these more lately

> /v1 /authorization untrusted client scope should fail if invalid scopes - should fail if invalid scopes
/home/circleci/project/packages/fxa-auth-server/test/oauth/api.js

https://app.circleci.com/pipelines/github/mozilla/fxa/13932/workflows/d4b8392f-79b0-4669-8451-0676ff99cc9c/jobs/196300

**Comment by data-sync-user** [comment]
➤ Vijay Budhram commented:

Another new one

>     lib/senders/sms: initialise: invalid data: wait a tick: called log.error correctly - called log.error correctly
    /home/circleci/project/packages/fxa-auth-server/test/local/senders/sms.js

AssertionError: expected 2 to equal 1
    at Context.<anonymous> (test/local/senders/sms.js:205:18)
    at processImmediate (internal/timers.js:456:21)https://app.circleci.com/pipelines/github/mozilla/fxa/13932/workflows/28039d32-3089-43d3-9eae-884d1a73136b/jobs/196314

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

I think there’s a few more since this was filed
