### ISSUE TITLE
fxa-js-client tests failing locally

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa#911]
Blocks #693.

Not sure if anyone else sees this or my installation is screwy but fwiw:

```
~/c/f/p/fxa-js-client (pb/693-new-entrypoint-params) $ npm t

> fxa-js-client@1.0.8 test /Users/philbooth/code/fxa/packages/fxa-js-client
> grunt test

Running "intern:node" (intern) task
Running with mocks...
FATAL ERROR
TypeError: Cannot read property 'hex' of undefined
  at <client/lib/credentials.js:12:30>
  at runFactory  <node_modules/dojo/dojo.js:1104:43>
  at execModule  <node_modules/dojo/dojo.js:1232:5>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at <node_modules/dojo/dojo.js:1267:6>
  at guardCheckComplete  <node_modules/dojo/dojo.js:1247:5>
Warning: FATAL ERROR
TypeError: Cannot read property 'hex' of undefined
  at <client/lib/credentials.js:12:30>
  at runFactory  <node_modules/dojo/dojo.js:1104:43>
  at execModule  <node_modules/dojo/dojo.js:1232:5>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at execModule  <node_modules/dojo/dojo.js:1223:12>
  at <node_modules/dojo/dojo.js:1267:6>
  at guardCheckComplete  <node_modules/dojo/dojo.js:1247:5> Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```

**Comment by philbooth** [comment]
This was because I hadn't run `npm run setup`. I completely forgot that the js-client required you to do that. I'm going to open a PR to move that into `postinstall` instead, so that other people don't make the same mistake in the future.
